//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: TimetableService.cs
// Generation date: 2013/07/11 11:25:25 NM.
namespace MobileNose
{
    
    /// <summary>
    /// There are no comments for TimetableContainer in the schema.
    /// </summary>
    public partial class TimetableService : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TimetableContainer object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TimetableService(System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TTCourse> Courses
        {
            get
            {
                if ((this._Courses == null))
                {
                    this._Courses = base.CreateQuery<TTCourse>("Courses");
                }
                return this._Courses;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TTCourse> _Courses;
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TTActivity> Activities
        {
            get
            {
                if ((this._Activities == null))
                {
                    this._Activities = base.CreateQuery<TTActivity>("Activities");
                }
                return this._Activities;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TTActivity> _Activities;
        /// <summary>
        /// There are no comments for Staff in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TTStaff> Staff
        {
            get
            {
                if ((this._Staff == null))
                {
                    this._Staff = base.CreateQuery<TTStaff>("Staff");
                }
                return this._Staff;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TTStaff> _Staff;
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TTGroup> Groups
        {
            get
            {
                if ((this._Groups == null))
                {
                    this._Groups = base.CreateQuery<TTGroup>("Groups");
                }
                return this._Groups;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TTGroup> _Groups;
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TTLocation> Locations
        {
            get
            {
                if ((this._Locations == null))
                {
                    this._Locations = base.CreateQuery<TTLocation>("Locations");
                }
                return this._Locations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TTLocation> _Locations;
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCourses(TTCourse tTCourse)
        {
            base.AddObject("Courses", tTCourse);
        }
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToActivities(TTActivity tTActivity)
        {
            base.AddObject("Activities", tTActivity);
        }
        /// <summary>
        /// There are no comments for Staff in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStaff(TTStaff tTStaff)
        {
            base.AddObject("Staff", tTStaff);
        }
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGroups(TTGroup tTGroup)
        {
            base.AddObject("Groups", tTGroup);
        }
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLocations(TTLocation tTLocation)
        {
            base.AddObject("Locations", tTLocation);
        }
    }
    /// <summary>
    /// There are no comments for TimetableData.Model.TTCourse in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class TTCourse
    {
        /// <summary>
        /// Create a new TTCourse object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="academicYear">Initial value of AcademicYear.</param>
        /// <param name="eC">Initial value of EC.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TTCourse CreateTTCourse(int ID, int academicYear, double eC)
        {
            TTCourse tTCourse = new TTCourse();
            tTCourse.ID = ID;
            tTCourse.AcademicYear = academicYear;
            tTCourse.EC = eC;
            return tTCourse;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property AcademicYear in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AcademicYear
        {
            get
            {
                return this._AcademicYear;
            }
            set
            {
                this.OnAcademicYearChanging(value);
                this._AcademicYear = value;
                this.OnAcademicYearChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AcademicYear;
        partial void OnAcademicYearChanging(int value);
        partial void OnAcademicYearChanged();
        /// <summary>
        /// There are no comments for Property CourseID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CourseID
        {
            get
            {
                return this._CourseID;
            }
            set
            {
                this.OnCourseIDChanging(value);
                this._CourseID = value;
                this.OnCourseIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CourseID;
        partial void OnCourseIDChanging(string value);
        partial void OnCourseIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Administration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Administration
        {
            get
            {
                return this._Administration;
            }
            set
            {
                this.OnAdministrationChanging(value);
                this._Administration = value;
                this.OnAdministrationChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Administration;
        partial void OnAdministrationChanging(string value);
        partial void OnAdministrationChanged();
        /// <summary>
        /// There are no comments for Property EC in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double EC
        {
            get
            {
                return this._EC;
            }
            set
            {
                this.OnECChanging(value);
                this._EC = value;
                this.OnECChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _EC;
        partial void OnECChanging(double value);
        partial void OnECChanged();
        /// <summary>
        /// There are no comments for Property CatalogNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CatalogNumber
        {
            get
            {
                return this._CatalogNumber;
            }
            set
            {
                this.OnCatalogNumberChanging(value);
                this._CatalogNumber = value;
                this.OnCatalogNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CatalogNumber;
        partial void OnCatalogNumberChanging(string value);
        partial void OnCatalogNumberChanged();
        /// <summary>
        /// There are no comments for Property Periods in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Periods
        {
            get
            {
                return this._Periods;
            }
            set
            {
                this.OnPeriodsChanging(value);
                this._Periods = value;
                this.OnPeriodsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Periods;
        partial void OnPeriodsChanging(string value);
        partial void OnPeriodsChanged();
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<TTActivity> Activities
        {
            get
            {
                return this._Activities;
            }
            set
            {
                if ((value != null))
                {
                    this._Activities = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<TTActivity> _Activities = new global::System.Collections.ObjectModel.Collection<TTActivity>();
    }
    /// <summary>
    /// There are no comments for TimetableData.Model.TTActivity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class TTActivity
    {
        /// <summary>
        /// Create a new TTActivity object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="duration">Initial value of Duration.</param>
        /// <param name="startTime">Initial value of StartTime.</param>
        /// <param name="day">Initial value of Day.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TTActivity CreateTTActivity(int ID, double duration, double startTime, int day)
        {
            TTActivity tTActivity = new TTActivity();
            tTActivity.ID = ID;
            tTActivity.Duration = duration;
            tTActivity.StartTime = startTime;
            tTActivity.Day = day;
            return tTActivity;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ActivityType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActivityType
        {
            get
            {
                return this._ActivityType;
            }
            set
            {
                this.OnActivityTypeChanging(value);
                this._ActivityType = value;
                this.OnActivityTypeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActivityType;
        partial void OnActivityTypeChanging(string value);
        partial void OnActivityTypeChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Duration;
        partial void OnDurationChanging(double value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property StartTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                this._StartTime = value;
                this.OnStartTimeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _StartTime;
        partial void OnStartTimeChanging(double value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// There are no comments for Property WeekPattern in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WeekPattern
        {
            get
            {
                return this._WeekPattern;
            }
            set
            {
                this.OnWeekPatternChanging(value);
                this._WeekPattern = value;
                this.OnWeekPatternChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WeekPattern;
        partial void OnWeekPatternChanging(string value);
        partial void OnWeekPatternChanged();
        /// <summary>
        /// There are no comments for Property Groups in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Groups
        {
            get
            {
                return this._Groups;
            }
            set
            {
                this.OnGroupsChanging(value);
                this._Groups = value;
                this.OnGroupsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Groups;
        partial void OnGroupsChanging(string value);
        partial void OnGroupsChanged();
        /// <summary>
        /// There are no comments for Property Day in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Day
        {
            get
            {
                return this._Day;
            }
            set
            {
                this.OnDayChanging(value);
                this._Day = value;
                this.OnDayChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Day;
        partial void OnDayChanging(int value);
        partial void OnDayChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TTCourse Course
        {
            get
            {
                return this._Course;
            }
            set
            {
                this._Course = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private TTCourse _Course;
        /// <summary>
        /// There are no comments for Staff in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<TTStaff> Staff
        {
            get
            {
                return this._Staff;
            }
            set
            {
                if ((value != null))
                {
                    this._Staff = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<TTStaff> _Staff = new global::System.Collections.ObjectModel.Collection<TTStaff>();
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<TTLocation> Locations
        {
            get
            {
                return this._Locations;
            }
            set
            {
                if ((value != null))
                {
                    this._Locations = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<TTLocation> _Locations = new global::System.Collections.ObjectModel.Collection<TTLocation>();
    }
    /// <summary>
    /// There are no comments for TimetableData.Model.TTStaff in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class TTStaff
    {
        /// <summary>
        /// Create a new TTStaff object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TTStaff CreateTTStaff(int ID)
        {
            TTStaff tTStaff = new TTStaff();
            tTStaff.ID = ID;
            return tTStaff;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Department in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Department
        {
            get
            {
                return this._Department;
            }
            set
            {
                this.OnDepartmentChanging(value);
                this._Department = value;
                this.OnDepartmentChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Department;
        partial void OnDepartmentChanging(string value);
        partial void OnDepartmentChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property TelephoneNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> TelephoneNumber
        {
            get
            {
                return this._TelephoneNumber;
            }
            set
            {
                this.OnTelephoneNumberChanging(value);
                this._TelephoneNumber = value;
                this.OnTelephoneNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _TelephoneNumber;
        partial void OnTelephoneNumberChanging(global::System.Nullable<int> value);
        partial void OnTelephoneNumberChanged();
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<TTActivity> Activities
        {
            get
            {
                return this._Activities;
            }
            set
            {
                if ((value != null))
                {
                    this._Activities = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<TTActivity> _Activities = new global::System.Collections.ObjectModel.Collection<TTActivity>();
    }
    /// <summary>
    /// There are no comments for TimetableData.Model.TTGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class TTGroup
    {
        /// <summary>
        /// Create a new TTGroup object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TTGroup CreateTTGroup(int ID)
        {
            TTGroup tTGroup = new TTGroup();
            tTGroup.ID = ID;
            return tTGroup;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Identifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identifier
        {
            get
            {
                return this._Identifier;
            }
            set
            {
                this.OnIdentifierChanging(value);
                this._Identifier = value;
                this.OnIdentifierChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identifier;
        partial void OnIdentifierChanging(string value);
        partial void OnIdentifierChanged();
        /// <summary>
        /// There are no comments for Property CatalogNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CatalogNumber
        {
            get
            {
                return this._CatalogNumber;
            }
            set
            {
                this.OnCatalogNumberChanging(value);
                this._CatalogNumber = value;
                this.OnCatalogNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CatalogNumber;
        partial void OnCatalogNumberChanging(string value);
        partial void OnCatalogNumberChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TTCourse Course
        {
            get
            {
                return this._Course;
            }
            set
            {
                this._Course = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private TTCourse _Course;
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<TTActivity> Activities
        {
            get
            {
                return this._Activities;
            }
            set
            {
                if ((value != null))
                {
                    this._Activities = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<TTActivity> _Activities = new global::System.Collections.ObjectModel.Collection<TTActivity>();
    }
    /// <summary>
    /// There are no comments for TimetableData.Model.TTLocation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class TTLocation
    {
        /// <summary>
        /// Create a new TTLocation object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="capacity">Initial value of Capacity.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TTLocation CreateTTLocation(int ID, int capacity)
        {
            TTLocation tTLocation = new TTLocation();
            tTLocation.ID = ID;
            tTLocation.Capacity = capacity;
            return tTLocation;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Capacity in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Capacity
        {
            get
            {
                return this._Capacity;
            }
            set
            {
                this.OnCapacityChanging(value);
                this._Capacity = value;
                this.OnCapacityChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Capacity;
        partial void OnCapacityChanging(int value);
        partial void OnCapacityChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property InfoURL in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InfoURL
        {
            get
            {
                return this._InfoURL;
            }
            set
            {
                this.OnInfoURLChanging(value);
                this._InfoURL = value;
                this.OnInfoURLChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InfoURL;
        partial void OnInfoURLChanging(string value);
        partial void OnInfoURLChanged();
        /// <summary>
        /// There are no comments for Activities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<TTActivity> Activities
        {
            get
            {
                return this._Activities;
            }
            set
            {
                if ((value != null))
                {
                    this._Activities = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<TTActivity> _Activities = new global::System.Collections.ObjectModel.Collection<TTActivity>();
    }
}
